
python unichars.py \p{Close_Punctuation}
python unichars.py \p{Currency_Symbol}
python unichars.py \p{IsAlnum}
python unichars.py \p{IsAlpha}
python unichars.py \p{IsLower}
python unichars.py \p{IsN}
python unichars.py \p{IsSc}
python unichars.py \p{IsSo}
python unichars.py \p{IsUpper}
python unichars.py \p{Open_Punctuation}
python unichars.py \p{Line_Separator}
python unichars.py \P{Number}
python unichars.py \p{Punctuation}
python unichars.py \p{Separator}

mv Close_Punctuation.txt charguana/data/perluniprops/
mv Currency_Symbol.txt charguana/data/perluniprops/
mv IsAlnum.txt charguana/data/perluniprops/
mv IsAlpha.txt charguana/data/perluniprops/
mv IsLower.txt charguana/data/perluniprops/
mv IsN.txt charguana/data/perluniprops/
mv IsSc.txt charguana/data/perluniprops/
mv IsSo.txt charguana/data/perluniprops/
mv IsUpper.txt charguana/data/perluniprops/
mv Open_Punctuation.txt charguana/data/perluniprops/
mv Line_Separator.txt charguana/data/perluniprops/
mv Number.txt charguana/data/perluniprops/
mv Punctuation.txt charguana/data/perluniprops/
mv Separator.txt charguana/data/perluniprops/
